name: Shree Dnyanoba Tukoba - workflows
on: [push, workflow_dispatch]
jobs:
  mauli-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create a directories
        run: mkdir -p basics/src/modules basics/src/controllers
      - name: Create chanting js file
        run: echo "console.log('Shree Dnyanoba Mauli Tukaram')" > mauli.js
      - name: Run Node.js file
        run: node mauli.js
      - name: List all files
        run: ls -a
      - name: Print great sant names
        run: echo Shree Nivrutti Dnyandev Sopan Muktabai Eknath Namdev Tukaram..!
      - name: Create db js file
        run: echo "console.log('This is a database connection config file')" > basics/db.js
      - name: Print working directory
        run: pwd
